# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import src.rpc.classifier_pb2 as classifier__pb2
import grpc


class NewsClassifierStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A rpc.Channel.
        """
        self.ClassifyNews = channel.unary_unary(
            "/NewsClassifier/ClassifyNews",
            request_serializer=classifier__pb2.NewsClassificationRequest.SerializeToString,
            response_deserializer=classifier__pb2.NewsClassificationReply.FromString,
        )


class NewsClassifierServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClassifyNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_NewsClassifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ClassifyNews": grpc.unary_unary_rpc_method_handler(
            servicer.ClassifyNews,
            request_deserializer=classifier__pb2.NewsClassificationRequest.FromString,
            response_serializer=classifier__pb2.NewsClassificationReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "NewsClassifier", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class NewsClassifier(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClassifyNews(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/NewsClassifier/ClassifyNews",
            classifier__pb2.NewsClassificationRequest.SerializeToString,
            classifier__pb2.NewsClassificationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
